from src.core.offerEngine.scheme import (
    SCHEME_PITCH, SCHEME_DETAILS, SCHEME_GIFTS, SCHEME_RULES, SCHEME_END,
    FAQ_SCHEME_WHAT, FAQ_SCHEME_WHEN, FAQ_SCHEME_HOW, FAQ_SCHEME_GIFTS,
    FAQ_SCHEME_COD, FAQ_SCHEME_COUPON, FAQ_SCHEME_TRUST,
)

__all__ = [
    "SCHEME_PITCH", "SCHEME_DETAILS", "SCHEME_GIFTS", "SCHEME_RULES", "SCHEME_END",
    "FAQ_SCHEME_WHAT", "FAQ_SCHEME_WHEN", "FAQ_SCHEME_HOW", "FAQ_SCHEME_GIFTS",
    "FAQ_SCHEME_COD", "FAQ_SCHEME_COUPON", "FAQ_SCHEME_TRUST",
]
