"""
Shared Pydantic models used across features.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class IndustryType(str, Enum):
    """Supported industry types for calling agents."""
    REAL_ESTATE = "real_estate"
    HOME_SERVICES = "home_services"
    FINTECH = "fintech"


class CallDirection(str, Enum):
    """Direction of a call."""
    INBOUND = "inbound"
    OUTBOUND = "outbound"


class CallStatus(str, Enum):
    """Status of a call."""
    INITIATED = "initiated"
    RINGING = "ringing"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    NO_ANSWER = "no_answer"
    BUSY = "busy"


class ConversationRole(str, Enum):
    """Role in a conversation message."""
    SYSTEM = "system"
    AGENT = "agent"
    USER = "user"


class ConversationMessage(BaseModel):
    """A single message in a conversation."""
    role: ConversationRole
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Optional[Dict[str, Any]] = None


class ConversationSession(BaseModel):
    """Represents a full conversation session."""
    session_id: str
    industry: IndustryType
    direction: CallDirection
    call_sid: Optional[str] = None
    caller_number: Optional[str] = None
    callee_number: Optional[str] = None
    messages: List[ConversationMessage] = Field(default_factory=list)
    status: CallStatus = CallStatus.INITIATED
    started_at: datetime = Field(default_factory=datetime.utcnow)
    ended_at: Optional[datetime] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class OutboundCallRequest(BaseModel):
    """Request model for initiating an outbound call."""
    industry: IndustryType
    to_number: str = Field(..., pattern=r"^\+?[1-9]\d{6,14}$")
    context: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None


class WebhookEvent(BaseModel):
    """Exotel webhook event payload."""
    call_sid: str = Field(..., alias="CallSid")
    call_status: Optional[str] = Field(None, alias="Status")
    direction: Optional[str] = Field(None, alias="Direction")
    from_number: Optional[str] = Field(None, alias="From")
    to_number: Optional[str] = Field(None, alias="To")
    date_created: Optional[str] = Field(None, alias="DateCreated")
    recording_url: Optional[str] = Field(None, alias="RecordingUrl")
    custom_field: Optional[str] = Field(None, alias="CustomField")

    class Config:
        populate_by_name = True


class WebSocketMessage(BaseModel):
    """WebSocket message exchanged with Exotel."""
    event: str
    stream_sid: Optional[str] = None
    call_sid: Optional[str] = None
    media: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None


class AgentResponse(BaseModel):
    """Response generated by an agent."""
    text: str
    audio_url: Optional[str] = None
    is_fallback: bool = False
    end_conversation: bool = False
    metadata: Optional[Dict[str, Any]] = None
